version: '3'
services:
  mongodb:
    image: mongo:3.4.14
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./conf/rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./conf/rabbitmq_delayed_message_exchange-20171201-3.7.x.ez:/usr/lib/rabbitmq/plugins/rabbitmq_delayed_message_exchange-20171201-3.7.x.ez
