spring:
  output.ansi.enabled: DETECT
  session.store-type: none

server:
  compression.enabled: true

# URI is of the form mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test
spring.data.mongodb.uri: mongodb://localhost/dcimporter

application:
  url: http://localhost:3000
  security:
    fetchUserInfo: true
  syncDelay: 10000
  
publik:
  formType: demande-de-rendez-vous-avec-un-elu
  secret: secret
  algo: sha256
  orig: ozwillo-dcimporter
  
  
# TODO : Copied pasted from portal configuration, check if we really need all of them
kernel:
  base_uri: https://kernel.ozwillo-preprod.eu
  alt_uri: ${kernel.base_uri}
  auth:
    issuer: ${kernel.base_uri}/
    auth_endpoint: ${kernel.alt_uri}/a/auth
    token_endpoint: ${kernel.base_uri}/a/token
    keys_endpoint: ${kernel.base_uri}/a/keys
    userinfo_endpoint: ${kernel.base_uri}/a/userinfo
    profile_endpoint: ${kernel.base_uri}/d/user
    password_change_endpoint: ${kernel.alt_uri}/a/password
    revoke_endpoint: ${kernel.base_uri}/a/revoke
    logout_endpoint: ${kernel.alt_uri}/a/logout
    callback_uri: ${application.url}/callback
    home_uri: ${application.url}
  user_directory_endpoint: ${kernel.base_uri}/d
  event_bus_endpoint: ${kernel.base_uri}/e
  notifications_endpoint: ${kernel.base_uri}/n
  client_id: dcimporter
  client_secret: secret
  # NB. once Datacore cache is in place, move datacore scope to its dedicated system user
  scopes_to_require: openid profile email address phone datacore

datacore:
  containerUrl: http://data.ozwillo.com
  url: https://data.ozwillo-preprod.eu
  systemAdminUser:  # Get it using Node.js lib / with DC importer clientId
    refreshToken: refreshToken
    nonce: changeit      #Set it when getting the refreshToken
